[package]
name = "raytrace"
version = "0.1.0"
authors = ["Peter Helbing <peter@abulafia.org>"]
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
image = "0.21.0"
rand = "0.6.5"
clap = "2.32.0"
num_cpus = "1.10.0"
pbr = "1.0.1"
humantime = "1.2.0"