[package]
name = "raytrace"
version = "0.1.0"
authors = ["Peter Helbing <peter@abulafia.org>"]
edition = "2018"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
clap = "2.33.0"
humantime = "2.0.0"
image = "0.23.4"
pbr = "1.0.2"
rand = "0.7.3"
rayon = "1.3.0"
